[book]
authors = ["marshmallow"]
language = "en"
multilingual = false
src = "src"
title = "wire"

[preprocessor]

[preprocessor.alerts]

[output]

[output.html]
additional-css = ["./theme/catppuccin.css", "./theme/catppuccin-alerts.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
git-repository-url = "https://git.althaea.zone/wires/wire"
git-repository-icon = "fa-code-fork"
edit-url-template = "https://git.althaea.zone/wires/wire/_edit/main/doc/{path}"
