[package]
name = "key_agent"
edition.workspace = true
version.workspace = true

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
prost = { workspace = true }
nix = { version = "0.30.1", features = ["user"] }

[build-dependencies]
prost-build = "0.14"
