#:schema https://json.schemastore.org/cargo.json
[package]
name = "wire-core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
no_web_tests = []
no_eval_tests = []

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
im = { workspace = true }
thiserror = "2.0.17"
derive_more = { version = "2.0.1", features = ["display"] }
wire-key-agent = { path = "../key_agent" }
futures = "0.3.31"
prost = { workspace = true }
gethostname = "1.1.0"
nix.workspace = true
miette = { workspace = true }
rand = "0.10.0"
tokio-util = { workspace = true }
portable-pty = "0.9.0"
anyhow.workspace = true
itertools = { workspace = true }
enum_dispatch = "0.3.13"
sha2 = { workspace = true }
base64 = { workspace = true }
nix-compat = { workspace = true }
aho-corasick = "1.1.4"
owo-colors = { workspace = true }
termion = "4.0.6"
sqlx = { version = "0.9", features = ["runtime-tokio", "sqlite"] }
zstd = "0.14.0"
wire-nix-client = { path = "../nix_client" }
memchr = "2"
semver = "1.0.28"
console = "0.16.4"

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
miette = { workspace = true }
syn = "3.0.0"
proc-macro2 = "1.0.103"
itertools = "0.15.0"
