---
name: Set up Nix
description: |
  Sets up the Nix environment for wire, removing unnecessary bloat and installing Nix along with proper
  substituters being set
inputs:
  cachixToken:
    description: Cachix token
    required: true
  withQEMU:
    description: Skip QEMU installation
    default: false
runs:
  using: "composite"
  steps:
    - uses: wimpysworld/nothing-but-nix@main
      with:
        hatchet-protocol: "carve"
    - name: Set up QEMU
      if: inputs.withQEMU == true
      uses: docker/setup-qemu-action@v3
    - name: Generate nix.conf
      shell: bash
      id: config
      run: |
        {
          echo 'config<<EOF'
          echo "system-features = nixos-test benchmark big-parallel kvm"

          if [ "${{ inputs.withQEMU }}" = "true" ]; then
            echo "extra-platforms = aarch64-linux i686-linux"
          fi

          echo EOF
        } >> "$GITHUB_OUTPUT"
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: ${{ steps.config.outputs.config }}
    - uses: cachix/cachix-action@v16
      with:
        name: wires
        authToken: "${{ inputs.cachixToken }}"
