---
name: Set up Nix
description: |
  Sets up the Nix environment for wire, removing unnecessary bloat and installing Nix along with proper
  substituters being set
inputs:
  cachixToken:
    description: Cachix token
    required: true
  withQEMU:
    description: Enable QEMU
    default: false
runs:
  using: "composite"
  steps:
    - uses: wimpysworld/nothing-but-nix@main
      with:
        hatchet-protocol: "carve"
    - name: Generate nix.conf
      shell: bash
      id: config
      run: |
        {
          echo 'config<<EOF'
          echo "system-features = nixos-test benchmark big-parallel kvm"

          if [ "${{ inputs.withQEMU }}" = "true" ]; then
            echo "extra-platforms = aarch64-linux i686-linux"
          fi

          echo EOF
        } >> "$GITHUB_OUTPUT"
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: ${{ steps.config.outputs.config }}
    - name: Sanity check nix.conf
      if: ${{ inputs.withQEMU == true && runner.debug == '1' }}
      shell: bash
      run: cat /etc/nix/nix.conf
    - name: Register binfmt
      if: inputs.withQEMU == true
      shell: bash
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - name: Sanity check binfmt
      if: ${{ inputs.withQEMU == true && runner.debug == '1' }}
      shell: bash
      run: |
        cat /proc/sys/fs/binfmt_misc/qemu-aarch64
    - uses: cachix/cachix-action@v16
      with:
        name: wires
        authToken: "${{ inputs.cachixToken }}"
