---
name: autofix.ci
on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      docs-pnpm: ${{ steps.filter.outputs.docs-pnpm }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs-pnpm:
              - 'doc/pnpm-lock.yaml'
  autofix:
    runs-on: ubuntu-latest
    needs: check-changes
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-nix
        with:
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: clippy --fix
        run: nix develop --print-build-logs -v --command cargo clippy --fix
      - name: nix fmt
        run: nix develop --print-build-logs -v --command pre-commit run --all-files
        continue-on-error: true
      - name: Upgrade Hash
        if: ${{ needs.check-changes.outputs.docs-pnpm == 'true' }}
        run: bash ./doc/upgrade.sh
      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
