name: "Build Packages"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [wire, docs]
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-env
      secrets: inherit
    - run: nix build .#${{ matrix.package }}
