---
name: "Build Packages"
on:
  pull_request:
  push:
jobs:
  pre-job:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"
          cancel_others: "true"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [wire, docs]
    needs: pre-job
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux i686-linux
      - uses: cachix/cachix-action@v16
        with:
          name: wires
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#${{ matrix.package }}
