name: "Build Packages"
on:
  pull_request:
  push:
jobs:
  pre-job:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"
          cancel_others: "true"
  agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: ["x86_64-linux", "aarch64-linux"]
    needs: pre-job
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y qemu-user-static
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            system = ${{ matrix.system }}
      - uses: cachix/cachix-action@v16
        with:
          name: wires
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#agent
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [wire, docs]
    needs: agent
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          name: wires
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix build .#${{ matrix.package }}
