---
name: "Build Packages"
on:
  pull_request:
  push:
jobs:
  pre-job:
    continue-on-error: true
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"
          cancel_others: "true"
  agent:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # https://github.com/nix-systems/default-linux
        system: ["x86_64-linux", "aarch64-linux"]
    needs: pre-job
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          withQEMU: true
      - run: nix build .#packages.${{ matrix.system }}.agent
  wire:
    runs-on: ubuntu-latest
    needs: agent
    strategy:
      matrix:
        # https://github.com/nix-systems/default-linux
        system: ["x86_64-linux", "aarch64-linux"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          withQEMU: true
      - run: nix build .#packages.${{ matrix.system }}.wire
  docs:
    runs-on: ubuntu-latest
    needs: pre-job
    if: needs.pre-job.outputs.should_skip != 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build .#docs
