name: "Build Packages"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [wire, docs]
    steps:
    - uses: actions/checkout@v4
    - uses: https://github.com/cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: https://github.com/cachix/install-nix-action@v27
    - uses: https://github.com/cachix/cachix-action@v14
      with:
        name: wires
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#${{ matrix.package }}
