name: Clean PR Environment
on:
  pull_request:
    types:
      - closed
jobs:
  cleanup-gh:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v5
      - name: get github app token
        uses: navikt/github-app-token-generator@793caf0d755fb4d6e88150825f680f188535cb48
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_CLEANER_ID }}
          private-key: ${{ secrets.GH_APP_CLEANER_PRIVATE_KEY }}
      - name: delete pr environment
        uses: strumwolf/delete-deployment-environment@v3.0.0
        with:
          token: ${{ steps.get-token.outputs.token }}
          environment: pr-${{ github.event.number }}
          ref: ${{ github.ref_name }}
