---
name: "Update package.nix Hash"
on:
  pull_request:
    paths: ["doc/pnpm-lock.yaml"]

jobs:
  upgrade-hash:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: ./.github/actions/setup-nix
        with:
          cachixToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Upgrade Hash
        run: bash ./doc/upgrade.sh
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update package.nix Hash
          file_pattern: "doc/package.nix"
