permissions:
  contents: read
  pull-requests: read
name: "Hydra"
on:
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - uses: jwalton/gh-find-current-pr@master
        id: find-pr
        with:
          state: all
      - name: Wait for build to succeed
        uses: autotelic/action-wait-for-status-check@v1
        if: contains(github.event.pull_request.labels.*.name, 'hydra')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          statusName: "ci/hydra:wire:pr_${{ steps.find-pr.outputs.number }}:packages.docs"
