name: "PR Preview"
on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      number: ${{ steps.find-pr.outputs.number }}

    steps:
      - uses: jwalton/gh-find-current-pr@master
        id: find-pr
        with:
          state: all

  deploy:
    runs-on: ubuntu-latest
    needs: check

    environment: 
      name: preview
      url: https://pr-${{ needs.check.outputs.number }}.wire-docs.pages.dev/

    if: ${{ needs.check.outputs.number != '' }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: wires
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#docs
      - name: Deploy to Cloudflare Pages
        id: deployment
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./result/ --project-name wire-docs --branch pr-${{ needs.check.outputs.number }}
